/* The following code was generated by JFlex 1.7.0 */

package arbolast;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexico.jflex</tt>
 */
public class AnalisisLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\1\47\1\3\1\3\22\0\1\3\1\0\1\45"+
    "\1\46\4\0\1\5\1\6\1\44\1\41\1\12\1\42\1\0\1\43"+
    "\12\1\1\11\1\0\1\37\1\36\1\40\2\0\2\2\1\30\11\2"+
    "\1\31\2\2\1\32\2\2\1\33\7\2\4\0\1\2\1\0\1\14"+
    "\1\2\1\17\1\2\1\20\1\27\1\2\1\16\1\23\2\2\1\22"+
    "\1\34\1\25\1\24\1\13\1\2\1\15\1\21\1\26\4\2\1\35"+
    "\1\2\1\7\1\0\1\10\7\0\1\47\u1fa2\0\1\47\1\47\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\6\3\1\13\3\3\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\1\1\4"+
    "\6\3\1\24\1\3\1\25\2\3\1\26\2\0\1\27"+
    "\7\3\1\30\1\3\1\0\1\31\1\3\1\32\12\3"+
    "\1\0\1\4\1\33\10\3\1\30\1\3\1\0\1\34"+
    "\21\3\1\35\1\3\1\36\1\3\1\37\1\3\1\40"+
    "\2\3\1\41\2\3\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\50\0\50\0\50"+
    "\0\50\0\50\0\50\0\310\0\360\0\u0118\0\u0140\0\u0168"+
    "\0\u0190\0\170\0\u01b8\0\u01e0\0\u0208\0\170\0\u0230\0\50"+
    "\0\50\0\50\0\50\0\u0258\0\50\0\u0280\0\u02a8\0\u02d0"+
    "\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398\0\170\0\u03c0\0\170"+
    "\0\u03e8\0\u0410\0\50\0\u0438\0\u0280\0\50\0\u0460\0\u0488"+
    "\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8"+
    "\0\170\0\u05f0\0\170\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8"+
    "\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\50\0\170"+
    "\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8"+
    "\0\170\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00"+
    "\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40"+
    "\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\170\0\u0c30\0\170"+
    "\0\u0c58\0\170\0\u0c80\0\170\0\u0ca8\0\u0cd0\0\170\0\u0cf8"+
    "\0\u0d20\0\170";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\2\4\1\15\1\16\1\17\1\20"+
    "\1\4\1\21\1\22\1\23\1\4\1\24\4\4\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\52\0\1\3\47\0\2\4\10\0\23\4"+
    "\15\0\2\5\44\0\2\4\10\0\1\4\1\40\21\4"+
    "\13\0\2\4\10\0\1\4\1\41\21\4\13\0\2\4"+
    "\10\0\1\4\1\42\7\4\1\43\11\4\13\0\2\4"+
    "\10\0\12\4\1\44\10\4\13\0\2\4\10\0\5\4"+
    "\1\45\2\4\1\46\12\4\13\0\2\4\10\0\21\4"+
    "\1\47\1\4\13\0\2\4\10\0\11\4\1\50\11\4"+
    "\13\0\2\4\10\0\10\4\1\51\12\4\13\0\2\4"+
    "\10\0\10\4\1\52\12\4\50\0\1\53\55\0\1\54"+
    "\3\0\45\55\1\56\2\55\4\37\1\0\43\37\1\0"+
    "\2\4\10\0\2\4\1\57\20\4\13\0\2\4\10\0"+
    "\4\4\1\60\16\4\13\0\2\4\10\0\6\4\1\61"+
    "\14\4\13\0\2\4\10\0\12\4\1\62\10\4\13\0"+
    "\2\4\10\0\13\4\1\63\7\4\13\0\2\4\10\0"+
    "\7\4\1\64\13\4\13\0\2\4\10\0\1\65\22\4"+
    "\13\0\2\4\10\0\12\4\1\66\10\4\13\0\2\4"+
    "\10\0\5\4\1\67\15\4\12\0\44\54\1\70\3\54"+
    "\1\0\2\4\10\0\1\4\1\71\21\4\13\0\2\4"+
    "\10\0\5\4\1\72\15\4\13\0\2\4\10\0\11\4"+
    "\1\73\11\4\13\0\2\4\10\0\4\4\1\74\6\4"+
    "\1\75\7\4\13\0\2\4\10\0\11\4\1\76\11\4"+
    "\13\0\2\4\10\0\5\4\1\77\15\4\13\0\2\4"+
    "\10\0\2\4\1\100\20\4\13\0\2\4\10\0\15\4"+
    "\1\101\1\102\1\103\1\104\2\4\13\0\2\4\10\0"+
    "\12\4\1\105\10\4\12\0\43\106\1\107\1\70\3\106"+
    "\1\0\2\4\10\0\2\4\1\110\20\4\13\0\2\4"+
    "\10\0\1\4\1\111\21\4\13\0\2\4\10\0\2\4"+
    "\1\112\20\4\13\0\2\4\10\0\12\4\1\113\10\4"+
    "\13\0\2\4\10\0\4\4\1\114\16\4\13\0\2\4"+
    "\10\0\10\4\1\115\12\4\13\0\2\4\10\0\1\4"+
    "\1\116\21\4\13\0\2\4\10\0\10\4\1\117\12\4"+
    "\13\0\2\4\10\0\1\4\1\120\21\4\13\0\2\4"+
    "\10\0\10\4\1\121\12\4\13\0\2\4\10\0\13\4"+
    "\1\122\7\4\12\0\44\106\1\123\3\106\1\0\2\4"+
    "\10\0\13\4\1\124\7\4\13\0\2\4\10\0\1\4"+
    "\1\125\21\4\13\0\2\4\10\0\4\4\1\126\16\4"+
    "\13\0\2\4\10\0\4\4\1\127\16\4\13\0\2\4"+
    "\10\0\21\4\1\130\1\4\13\0\2\4\10\0\6\4"+
    "\1\131\14\4\13\0\2\4\10\0\5\4\1\132\15\4"+
    "\13\0\2\4\10\0\2\4\1\133\20\4\13\0\2\4"+
    "\10\0\2\4\1\134\20\4\12\0\43\106\1\107\1\0"+
    "\3\106\1\0\2\4\10\0\5\4\1\135\15\4\13\0"+
    "\2\4\10\0\2\4\1\136\20\4\13\0\2\4\10\0"+
    "\5\4\1\137\15\4\13\0\2\4\10\0\10\4\1\140"+
    "\12\4\13\0\2\4\10\0\10\4\1\141\12\4\13\0"+
    "\2\4\10\0\11\4\1\121\11\4\13\0\2\4\10\0"+
    "\12\4\1\142\10\4\13\0\2\4\10\0\1\4\1\121"+
    "\21\4\13\0\2\4\10\0\1\4\1\143\21\4\13\0"+
    "\2\4\10\0\12\4\1\144\10\4\13\0\2\4\10\0"+
    "\10\4\1\145\12\4\13\0\2\4\10\0\6\4\1\146"+
    "\14\4\13\0\2\4\10\0\11\4\1\147\11\4\13\0"+
    "\2\4\10\0\2\4\1\150\20\4\13\0\2\4\10\0"+
    "\13\4\1\151\7\4\13\0\2\4\10\0\6\4\1\152"+
    "\14\4\13\0\2\4\10\0\1\4\1\153\21\4\13\0"+
    "\2\4\10\0\11\4\1\154\11\4\13\0\2\4\10\0"+
    "\12\4\1\155\10\4\13\0\2\4\10\0\2\4\1\156"+
    "\20\4\13\0\2\4\10\0\2\4\1\157\20\4\13\0"+
    "\2\4\10\0\1\4\1\160\21\4\13\0\2\4\10\0"+
    "\1\4\1\161\21\4\13\0\2\4\10\0\2\4\1\162"+
    "\20\4\13\0\2\4\10\0\6\4\1\121\14\4\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\6\11\14\1\4\11\1\1\1\11"+
    "\15\1\1\11\2\0\1\11\11\1\1\0\15\1\1\0"+
    "\1\11\13\1\1\0\37\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  ComplexSymbolFactory symbolFactory;
  
  public void setSymbolFactory(ComplexSymbolFactory sf){
      symbolFactory = sf;
  }

  private Symbol symbol(String name, int sym) {
      return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+yylength(),yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline+1,yycolumn+1,yychar);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    System.out.println("Error en línea "+(yyline+1)+", columna "+(yycolumn+1)+" carácter: "+message);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisisLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", Simbolo.EOF, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+1,yychar+1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error(yytext());
            } 
            // fall through
          case 35: break;
          case 2: 
            { return symbol("ENTERO",Simbolo.ENTERO, yytext());
            } 
            // fall through
          case 36: break;
          case 3: 
            { return symbol("ID",Simbolo.ID, yytext());
            } 
            // fall through
          case 37: break;
          case 4: 
            { 
            } 
            // fall through
          case 38: break;
          case 5: 
            { return symbol("PARENTESIS_ABIERTO",Simbolo.PARENTESIS_ABIERTO);
            } 
            // fall through
          case 39: break;
          case 6: 
            { return symbol("PARENTESIS_CERRADO",Simbolo.PARENTESIS_CERRADO);
            } 
            // fall through
          case 40: break;
          case 7: 
            { return symbol("LLAVE_ABIERTA", Simbolo.LLAVE_ABIERTA);
            } 
            // fall through
          case 41: break;
          case 8: 
            { return symbol("LLAVE_CERRADA", Simbolo.LLAVE_CERRADA);
            } 
            // fall through
          case 42: break;
          case 9: 
            { return symbol("DOS_PUNTOS", Simbolo.DOS_PUNTOS);
            } 
            // fall through
          case 43: break;
          case 10: 
            { return symbol("COMA",Simbolo.COMA);
            } 
            // fall through
          case 44: break;
          case 11: 
            { return symbol("O",Simbolo.O);
            } 
            // fall through
          case 45: break;
          case 12: 
            { return symbol("Y",Simbolo.Y);
            } 
            // fall through
          case 46: break;
          case 13: 
            { return symbol("IGUAL",Simbolo.IGUAL);
            } 
            // fall through
          case 47: break;
          case 14: 
            { return symbol("MENOR",Simbolo.MENOR);
            } 
            // fall through
          case 48: break;
          case 15: 
            { return symbol("MAYOR",Simbolo.MAYOR);
            } 
            // fall through
          case 49: break;
          case 16: 
            { return symbol("MAS",Simbolo.MAS);
            } 
            // fall through
          case 50: break;
          case 17: 
            { return symbol("MENOS",Simbolo.MENOS);
            } 
            // fall through
          case 51: break;
          case 18: 
            { return symbol("DIVISION",Simbolo.DIVISION);
            } 
            // fall through
          case 52: break;
          case 19: 
            { return symbol("ASTERISCO",Simbolo.ASTERISCO);
            } 
            // fall through
          case 53: break;
          case 20: 
            { return symbol("SI",Simbolo.SI);
            } 
            // fall through
          case 54: break;
          case 21: 
            { return symbol("NO",Simbolo.NO);
            } 
            // fall through
          case 55: break;
          case 22: 
            { return symbol("IGUAL_IGUAL",Simbolo.IGUAL_IGUAL);
            } 
            // fall through
          case 56: break;
          case 23: 
            { String t = yytext();
                return symbol("CADENA",Simbolo.CADENA, t.substring(1, t.length() - 1));
            } 
            // fall through
          case 57: break;
          case 24: 
            { return symbol("FIN",Simbolo.FIN);
            } 
            // fall through
          case 58: break;
          case 25: 
            { return symbol("PARA", Simbolo.PARA);
            } 
            // fall through
          case 59: break;
          case 26: 
            { return symbol("CASO", Simbolo.CASO);
            } 
            // fall through
          case 60: break;
          case 27: 
            { return symbol("HACER", Simbolo.HACER);
            } 
            // fall through
          case 61: break;
          case 28: 
            { return symbol("CONCAT",Simbolo.CONCAT);
            } 
            // fall through
          case 62: break;
          case 29: 
            { return symbol("ENTONCES",Simbolo.ENTONCES);
            } 
            // fall through
          case 63: break;
          case 30: 
            { return symbol("IMPRIMIR",Simbolo.IMPRIMIR);
            } 
            // fall through
          case 64: break;
          case 31: 
            { return symbol("MIENTRAS",Simbolo.MIENTRAS);
            } 
            // fall through
          case 65: break;
          case 32: 
            { return symbol("CONTRARIO", Simbolo.CONTRARIO);
            } 
            // fall through
          case 66: break;
          case 33: 
            { return symbol("CONCATENAR",Simbolo.CONCATENAR);
            } 
            // fall through
          case 67: break;
          case 34: 
            { return symbol("SELECCIONAR", Simbolo.SELECCIONAR);
            } 
            // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
