
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package arbolast;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CASO = 30;
  public static final int Y = 16;
  public static final int CONCAT = 36;
  public static final int IMPRIMIR = 14;
  public static final int ENTERO = 37;
  public static final int SI = 5;
  public static final int O = 15;
  public static final int DOS_PUNTOS = 32;
  public static final int ENTONCES = 6;
  public static final int ASTERISCO = 25;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FIN = 7;
  public static final int LLAVE_ABIERTA = 33;
  public static final int HASTA = 35;
  public static final int IGUAL = 21;
  public static final int FINMIENTRAS = 11;
  public static final int FINPARA = 8;
  public static final int MIENTRAS = 12;
  public static final int CONTRARIO = 31;
  public static final int SELECCIONAR = 29;
  public static final int ID = 39;
  public static final int PUNTO_COMA = 26;
  public static final int IGUAL_IGUAL = 18;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FINCASO = 9;
  public static final int COMA = 4;
  public static final int CADENA = 38;
  public static final int MENOS = 23;
  public static final int MENOR = 19;
  public static final int CONCATENAR = 13;
  public static final int MAYOR = 20;
  public static final int NO = 17;
  public static final int HACER = 28;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int PARA = 27;
  public static final int LLAVE_CERRADA = 34;
  public static final int FINSI = 10;
  public static final int DIVISION = 24;
  public static final int MAS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "SI",
  "ENTONCES",
  "FIN",
  "FINPARA",
  "FINCASO",
  "FINSI",
  "FINMIENTRAS",
  "MIENTRAS",
  "CONCATENAR",
  "IMPRIMIR",
  "O",
  "Y",
  "NO",
  "IGUAL_IGUAL",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "ASTERISCO",
  "PUNTO_COMA",
  "PARA",
  "HACER",
  "SELECCIONAR",
  "CASO",
  "CONTRARIO",
  "DOS_PUNTOS",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "HASTA",
  "CONCAT",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

