
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package arbolast;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int MENOS = 11;
  public static final int MENOR = 8;
  public static final int CADENA = 3;
  public static final int INT = 29;
  public static final int IGUAL = 6;
  public static final int CHAR = 30;
  public static final int COMO = 15;
  public static final int HASTA = 28;
  public static final int ENTONCES = 18;
  public static final int IMPRIMIR = 16;
  public static final int PARA = 27;
  public static final int ID = 2;
  public static final int BOOLEAN = 31;
  public static final int CARACTER = 5;
  public static final int STRING = 32;
  public static final int CASO = 22;
  public static final int ASIGNACION = 13;
  public static final int FINSELECCIONAR = 24;
  public static final int FINMIENTRAS = 26;
  public static final int MAYOR = 7;
  public static final int EOF = 0;
  public static final int MAYORIGUAL = 9;
  public static final int SI = 17;
  public static final int error = 1;
  public static final int NUMERO = 4;
  public static final int PUNTOCOMA = 12;
  public static final int DIM = 14;
  public static final int NO = 19;
  public static final int MIENTRAS = 25;
  public static final int FINSI = 20;
  public static final int FINCASO = 23;
  public static final int MAS = 10;
  public static final int SELECCIONAR = 21;
  public static final int DOUBLE = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CADENA",
  "NUMERO",
  "CARACTER",
  "IGUAL",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MAS",
  "MENOS",
  "PUNTOCOMA",
  "ASIGNACION",
  "DIM",
  "COMO",
  "IMPRIMIR",
  "SI",
  "ENTONCES",
  "NO",
  "FINSI",
  "SELECCIONAR",
  "CASO",
  "FINCASO",
  "FINSELECCIONAR",
  "MIENTRAS",
  "FINMIENTRAS",
  "PARA",
  "HASTA",
  "INT",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "DOUBLE"
  };
}

