
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package arbolast;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CASO = 29;
  public static final int CONCAT = 9;
  public static final int IMPRIMIR = 40;
  public static final int ENTERO = 42;
  public static final int SI = 38;
  public static final int CASE = 23;
  public static final int DOS_PUNTOS = 25;
  public static final int ASTERISCO = 18;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FOR = 20;
  public static final int LLAVE_ABIERTA = 26;
  public static final int HASTA = 35;
  public static final int SIGUIENTE = 36;
  public static final int NOT = 12;
  public static final int AND = 11;
  public static final int IGUAL = 16;
  public static final int FINMIENTRAS = 33;
  public static final int FINPARA = 37;
  public static final int OR = 10;
  public static final int MIENTRAS = 32;
  public static final int CONTRARIO = 30;
  public static final int SELECCIONAR = 28;
  public static final int IF = 5;
  public static final int ID = 44;
  public static final int PUNTO_COMA = 19;
  public static final int IGUAL_IGUAL = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FINCASO = 31;
  public static final int COMA = 4;
  public static final int CADENA = 43;
  public static final int MENOR = 14;
  public static final int SWITCH = 22;
  public static final int MAYOR = 15;
  public static final int NO = 39;
  public static final int ELSE = 6;
  public static final int WHILE = 8;
  public static final int DEFAULT = 24;
  public static final int END = 7;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int PARA = 34;
  public static final int LLAVE_CERRADA = 27;
  public static final int FINSI = 41;
  public static final int DO = 21;
  public static final int MAS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "IF",
  "ELSE",
  "END",
  "WHILE",
  "CONCAT",
  "OR",
  "AND",
  "NOT",
  "IGUAL_IGUAL",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "ASTERISCO",
  "PUNTO_COMA",
  "FOR",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DOS_PUNTOS",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "SELECCIONAR",
  "CASO",
  "CONTRARIO",
  "FINCASO",
  "MIENTRAS",
  "FINMIENTRAS",
  "PARA",
  "HASTA",
  "SIGUIENTE",
  "FINPARA",
  "SI",
  "NO",
  "IMPRIMIR",
  "FINSI",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

