
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package arbolast;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CHAR = 32;
  public static final int CONCAT = 9;
  public static final int IMPRIMIR = 10;
  public static final int ENTERO = 37;
  public static final int DIFERENTE = 36;
  public static final int CASE = 24;
  public static final int DOUBLE = 33;
  public static final int DOS_PUNTOS = 28;
  public static final int INT = 34;
  public static final int ASTERISCO = 19;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FOR = 21;
  public static final int LLAVE_ABIERTA = 26;
  public static final int NOT = 13;
  public static final int AND = 12;
  public static final int IGUAL = 17;
  public static final int OR = 11;
  public static final int COMO = 30;
  public static final int IF = 5;
  public static final int ID = 39;
  public static final int PUNTO_COMA = 20;
  public static final int IGUAL_IGUAL = 14;
  public static final int DIM = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int CADENA = 38;
  public static final int MENOR = 15;
  public static final int SWITCH = 23;
  public static final int MAYOR = 16;
  public static final int ELSE = 6;
  public static final int WHILE = 8;
  public static final int DEFAULT = 25;
  public static final int END = 7;
  public static final int STRING = 35;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int LLAVE_CERRADA = 27;
  public static final int DO = 22;
  public static final int MAS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "IF",
  "ELSE",
  "END",
  "WHILE",
  "CONCAT",
  "IMPRIMIR",
  "OR",
  "AND",
  "NOT",
  "IGUAL_IGUAL",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "ASTERISCO",
  "PUNTO_COMA",
  "FOR",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "DOS_PUNTOS",
  "DIM",
  "COMO",
  "BOOLEAN",
  "CHAR",
  "DOUBLE",
  "INT",
  "STRING",
  "DIFERENTE",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

